# @name GetAccounts
GET http://localhost:8080/v1/accounts
###

# @name GetAccountByID
GET http://localhost:8080/v1/accounts/1
###

# @name CreateAccount
POST http://localhost:8080/v1/accounts
Content-Type: application/json

{
    "name": "Foo",
    "initial_value": 10.0
}
###

# @name UpdateAccountByID
PUT http://localhost:8080/v1/accounts/1
Content-Type: application/json

{
    "name": "Foo",
    "current_value": 5.0
}
###

# @name DeleteAccountByID
DELETE http://localhost:8080/v1/accounts/1
###

# @name GetTransactionsByAccountID
GET http://localhost:8080/v1/accounts/1/transactions
###

# @name GetTransactionsByIDAndAccountID
GET http://localhost:8080/v1/accounts/1/transactions/1
###

# @name CreateTransaction
POST http://localhost:8080/v1/accounts/1/transactions
Content-Type: application/json

{
    "name": "Sell",
    "value": 10.0
}
###

# @name DeleteTransactionByIDAndAccountID
DELETE http://localhost:8080/v1/accounts/1/transactions/1
###
